language: android
sudo: required
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.2
  - android-27

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

  # Emulator for the tests
  - sys-img-armeabi-v7a-android-23

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

cache:
  directories:
    - $HOME/.gradle/caches/3.3
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager "platforms;android-27"

install:
#   - sdkmanager --list || true
#   - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
#   - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"


#before_script:
#  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &

script:

# Instrumentation tests
#  - ./gradlew check -PdisablePreDex --continue --stacktrace
#  - android-wait-for-emulator
#  - adb devices
#  - adb shell input keyevent 82 &
#  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
#  - rm /home/travis/.gradle/caches/2.8/plugin-resolution/cache.properties.lock
# Unit tests
#  - ./gradlew testDevReleaseUnitTest -q
# If successful and Git TAG ends with "BETA" - release to Crashlytics BETA
#  - '[[ $TRAVIS_TAG != *BETA ]]  || ./gradlew assembleLiveRelease crashlyticsUploadDistributionLiveRelease -q'
#
  - './gradlew assembleRostiDebug'
